✨ feat: Show Apartment Details on Result Page
CodeSoom/project-react-3-dodoongtak pull request #50
Opened 2021-04-06 07:56 UTC by dodoongtak

Users can now check out the details of the apartment which they select on the apartment page.

If Users haven't filled up the form yet, the result screen shows a link to enter their information.

![apartment details](https://user-images.githubusercontent.com/77006427/113677437-8b6a7e00-96f8-11eb-8690-1213ad6648a5.gif)

2021-04-06 15:27 UTC, Kihyun92 requested changes

2021-04-06 15:27 UTC, Kihyun92 commented on src/App.jsx
>            <Route path="/apartment/:id" component={ApartmentPage} />
상세 페이지인가요? RESTful 하게 `apartments/:id`와 같이 복수형으로 처리하는게 좋을 것 같아요~

2021-04-06 15:27 UTC, Kihyun92 commented on src/components/LinkField.jsx
> +    }
특정 경우에만 changeApartment()가 실행되는건가요?
그럼 title이 보기인 경우에만 사용하는 곳에서 changeApartment를 주입해주고
이 핸들러 함수에서는 changeApartment가 있는 경우에만 호출하도록 처리할 수도 있을 것 같아요.
`changeApartment?.(apartment);`

아니면 props로 onClick을 넘겨주고 있으니 onClick에 title이 보기인 경우에만 핸들링하는 로직을 넣어서 넘기는 방법도 있을 것 같아요.

2021-04-06 15:27 UTC, Kihyun92 commented on src/pages/Apartment/Apartments.jsx
> +        <article key={apartment.name}>
아파트 name이 key가 되는건가요? 아파트 이름이 겹치는 케이스는 없을까요?

아니라면 id 프로퍼티를 추가해서 사용해도 좋을 것 같네요 ㅎㅎ

2021-04-06 15:27 UTC, Kihyun92 commented on src/pages/Home/Greet.jsx
> +  );
오잉 조금 햇갈리는데, isNew에 따른 예외처리가 둘다 들어가네요. 이 경우에는 한쪽의 예외처리를 없애거나, 삼항연산자로 처리해주는건 어떨까요?

2021-04-06 17:04 UTC, dodoongtak commented
rebase 설정 잘못으로 인해 force push 불가.

reflog로 탐색해도 rebase 전 커밋으로 변경 불가능....

다음에는 좀 더 주의하도록하겠습니다...

2021-04-06 17:04 UTC, merged

2021-04-06 17:29 UTC, dodoongtak commented on src/pages/Home/Greet.jsx
> +  );
이미 `isNew` 상태값에 따라 전처리를 하기 떄문에, 하단에 단락평가는 삭제가 옳다.

2021-04-06 17:30 UTC, dodoongtak commented on src/pages/Apartment/Apartments.jsx
> +        <article key={apartment.name}>
아파트 이름이 중복될 가능성은 희박하다.

절대란 없으니, 추후에 백엔드에서 data를 가공할떄, id를 넣어주도록 수정 예정.

2021-04-06 17:31 UTC, dodoongtak commented on src/App.jsx
>            <Route path="/apartment/:id" component={ApartmentPage} />
[Restful 참고링크](https://restfulapi.net/resource-naming/)

collection(집합)을 먼저 표현하고, 
그 집합 중에 특정한 1개는 id(식별자)로 구분하는 방식.

2021-04-07 00:00 UTC, dodoongtak commented on src/components/LinkField.jsx
> +    }
#42 반영 완료!